name: flutter_test_ptbionic
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter_iconly: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  flutter_form_builder: ^9.0.0
  flutter_native_splash: ^2.2.19
  flutter_secure_storage: ^8.0.0
  form_builder_validators: 9.0.0
  get: ^4.6.5
  get_storage: ^2.1.1
  google_nav_bar: ^5.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  modal_progress_hud_nsn: ^0.4.0
  pull_to_refresh: ^2.0.0
  sizer: ^2.0.15
  table_calendar: ^3.0.9

flutter_gen:
  output: lib/resources/

dev_dependencies:
  build_runner: any
  flutter_gen_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - lib/resources/images/